server:
  port: 9080

spring:
  application:
    name: evaccine-user-service

  datasource:
    url: jdbc:h2:mem:evaccine
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true