server:
  port: 9090
  
spring:
  application:
    name: eVaccine-admin-service
    

  datasource:
    url: jdbc:h2:mem:evaccine
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect    
  h2:
    console.enabled: true
  